image: node:latest

before_script:
  - export NODE_ENV=test

variables:
  DB_HOST: $DB_URL
  DB_PORT: 27017

stages:
  - build
  - test
  - deploy

cache:
  paths:
    - node_modules/

services:
  - mongo

install_dependencies:
  stage: build
  script:
    - npm install
  artifacts:
    paths:
      - node_modules/

test_with_lab:
  stage: test
  script:
    - npm test

heroku_deploy:
  stage: deploy
  image: ruby:latest
  script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
    - dpl --provider=heroku --app=$APP_NAME --api-key=$AUTH_TOKEN
  only:
    - master
